### ISSUE TITLE
Is there a way to download the installer on the website, pip download fails

### ISSUE THREAD

**Issue by xrz14** [Protein-Engineering-Framework/PyPEF#1]

**Comment by niklases** [comment]
Hi, 

which operating system and which Python version are you using (Python version should be >= 3.10)?

Can you try to create a new environment with Python>=3.10 and run `pip install -r requirements.txt` followed by `python run.py` (or `pip install -e .`)?

You can also try the setup script based on your OS used (/scripts/Setup; for Windows just run the [conda_install_test.bat](https://github.com/Protein-Engineering-Framework/PyPEF/blob/master/scripts/Setup/windows/conda_install_test.bat) and for Linux follow the steps in [conda_install_test.sh](https://github.com/Protein-Engineering-Framework/PyPEF/blob/master/scripts/Setup/linux/conda_install_test.sh)).

Hope this helps!

**Comment by xrz14** [comment]
Thank you for your prompt reply, my Windows system, read your suggestion, I will try to install the new python 3.10 and configure the new environment to see if that solves the problem. Thank you again.

**Comment by niklases** [comment]
Perfect, if it is a Python package dependecy issue you can try to "force" package versions using the provided environment YAML file and Conda: Go into the downloaded and unzipped repository and try `conda env create -f win_env.yml`, `conda activate pypef`, and `python run.py` (now you should be able to run all required commands, e.g., such as `python run.py --version`).

**Comment by niklases** [comment]
Closing issue
